spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/bugboard26}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:"password_locale"}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=${JWT_SECRET:BugBoard26JwtSecretKeyForDevelopmentOnlyChangeMe123456789}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

app.default-admin.email=${DEFAULT_ADMIN_EMAIL:admin@bugboard26.it}
app.default-admin.password=${DEFAULT_ADMIN_PASSWORD:Admin123!}

bugboard.upload-dir=${UPLOAD_DIR:uploads/issues}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

server.port=${PORT:8080}
