spring.datasource.url=jdbc:postgresql://localhost:5432/bugboard26
spring.datasource.username=postgres
spring.datasource.password=elapapVito6.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=BugBoard26JwtSecretKeyForDevelopmentOnlyChangeMe123456789
app.jwt.expiration-ms=86400000

app.default-admin.email=admin@bugboard26.it
app.default-admin.password=Admin123!

bugboard.upload-dir=uploads/issues
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
